services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: bonsartisans
      MONGO_INITDB_ROOT_PASSWORD: testtechnique